[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://skill-companion-backend.up.railway.app"
  REACT_APP_GEMINI_API_KEY = "AIzaSyCa3VtgQ_M6Z0pvHAVrhYFNNvm64F4pi-E"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 