services:
  # Backend API Service
  - type: web
    name: skill-companion-backend
    env: node
    plan: free
    buildCommand: ./backend/render-build.sh
    startCommand: cd backend && node server.js
    repo: https://github.com/Harshverma1208/skill-companion-project.git
    branch: main
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://skill-companion-frontend.onrender.com

  # Frontend Service
  - type: web
    name: skill-companion-frontend
    env: static
    plan: free
    buildCommand: ./frontend/render-build.sh
    staticPublishPath: ./frontend/build
    repo: https://github.com/Harshverma1208/skill-companion-project.git
    branch: main
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: REACT_APP_API_URL
        value: https://skill-companion-backend.onrender.com
      - key: REACT_APP_GEMINI_API_KEY
        value: AIzaSyCa3VtgQ_M6Z0pvHAVrhYFNNvm64F4pi-E 